#Originally from https://raw.githubusercontent.com/intel/multus-cni/master/.github/workflows/go-build-test-amd64.yml
name: Go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 8 * * 0" # every sunday
jobs:
  build-test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
        goos: [linux]
        goarch: [amd64, arm64, ppc64le]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build test for ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: GOARCH="${TARGET}" make build

      - name: Go test
        if: ${{ matrix.goarch }} == "amd64"
        run: sudo make test-race # sudo needed for netns change in test

  coverage:
    runs-on: ubuntu-latest
    needs: build-test
    name: coverage
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v3

      - name: Go test with coverage
        run: sudo make test-coverage # sudo needed for netns change in test
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: test/coverage/cover.out
