#Originally from https://raw.githubusercontent.com/intel/multus-cni/master/.github/workflows/go-build-test-amd64.yml
name: Go-build-and-test-amd64
on:
    push:
    pull_request:
    schedule:
      - cron: "0 8 * * 0" # every sunday
jobs:
  build-test:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest]
        goos: [linux]
        goarch: [amd64, arm64, ppc64le]
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build test for ${{ matrix.goarch }}
        env:
          GOARCH: ${{ matrix.goarch }}
          GOOS: ${{ matrix.goos }}
        run: GOARCH="${TARGET}" go build ./cmd/sriov/...

      - name: Go test
        if: ${{ matrix.goarch }} == "amd64"
        run: sudo go test -race ./... # sudo needed for netns change in test

  coverage:
    runs-on: ubuntu-latest
    needs: build-test
    name: coverage
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go test with coverage
        run: sudo make test-coverage # sudo needed for netns change in test
      
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: test/coverage/lcov.info

  sriov-operator-e2e-test:
    name: SR-IOV operator e2e tests
    needs: [ build-test ]
    runs-on: [ sriov ]
    env:
      TEST_REPORT_PATH: k8s-artifacts
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: build sriov-cni image
        run: podman build -t ghaction-sriov-cni:pr-${{github.event.pull_request.number}} .
  
      - name: Check out sriov operator's code
        uses: actions/checkout@v2
        with:
          repository: k8snetworkplumbingwg/sriov-network-operator
          path: sriov-network-operator-wc

      - name: run test
        run: make test-e2e-conformance-virtual-k8s-cluster-ci
        working-directory: sriov-network-operator-wc
        env:
          LOCAL_SRIOV_CNI_IMAGE: ghaction-sriov-cni:pr-${{github.event.pull_request.number}}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ env.TEST_REPORT_PATH }}
          path: ./sriov-network-operator-wc/${{ env.TEST_REPORT_PATH }}
