name: Go-static-analysis
on: [push, pull_request]
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v2
      - name: run make lint
        run: make lint
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
    - uses: actions/checkout@v2
    - uses: brpaz/hadolint-action@v1.2.1
      name: Run Hadolint
      with:
       dockerfile: Dockerfile
